/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package lab1.derby;
import lab1.derby.DbManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import lab1.derby.DbManager;


/**
 *
 * @author student
 */
public class dbAktualizuj extends javax.swing.JFrame {
    private boolean connect;
    /**
     * Creates new form dbDodaj
     */
    public dbAktualizuj() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        infoLabel = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        fieldName = new javax.swing.JTextField();
        fieldAuthor = new javax.swing.JTextField();
        fieldGendre = new javax.swing.JTextField();
        fieldMaterial = new javax.swing.JTextField();
        fieldUSD = new javax.swing.JTextField();
        checkboxMP = new javax.swing.JCheckBox();
        bttnUpdateSculpture = new javax.swing.JButton();
        labelInfo = new javax.swing.JLabel();
        fieldID = new javax.swing.JTextField();

        fieldName.setText("Name");
        fieldName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fieldNameActionPerformed(evt);
            }
        });

        fieldAuthor.setText("Author");
        fieldAuthor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fieldAuthorActionPerformed(evt);
            }
        });

        fieldGendre.setText("Gendre");

        fieldMaterial.setText("Material");

        fieldUSD.setText("USD price");

        checkboxMP.setText("Museum property");

        bttnUpdateSculpture.setText("Update Sculpture");
        bttnUpdateSculpture.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bttnUpdateSculptureActionPerformed(evt);
            }
        });

        fieldID.setText("ID");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(fieldID, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(fieldName, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(fieldAuthor, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(fieldGendre, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(fieldMaterial, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(fieldUSD, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(labelInfo))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(bttnUpdateSculpture)
                    .addComponent(checkboxMP))
                .addGap(0, 8, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(12, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(fieldName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(fieldAuthor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(fieldGendre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(fieldMaterial, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(fieldUSD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(checkboxMP)
                    .addComponent(fieldID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bttnUpdateSculpture)
                    .addComponent(labelInfo)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(infoLabel)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(infoLabel)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void fieldNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fieldNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fieldNameActionPerformed

    private void fieldAuthorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fieldAuthorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fieldAuthorActionPerformed

    private void bttnUpdateSculptureActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bttnUpdateSculptureActionPerformed
        // TODO add your handling code here:
        try {
            // TODO add your handling code here:
            connect = DbManager.Connect();
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(DbOkno.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(DbOkno.class.getName()).log(Level.SEVERE, null, ex);
        }
        if (connect) {
            labelInfo.setText("Połączono");
        } else {
            labelInfo.setText("Nie połączono");
        }
        
        try {
            Statement st = null;
            
            int aktualizuj = 0;
            st = DbManager.conn.createStatement();
            /*String author = fieldAuthor.getText();
            System.out.println(author);
            if(!author.equals("Author")&&(fieldAuthor.getText()).length()>0)
            {
                aktualizuj = st.executeUpdate("UPDATE app.sculptures SET author = '"+fieldAuthor.getText()+"' WHERE sculpture_id  = "+fieldID.getText());
                labelInfo.setText("Zaktualizowano rzezbe o  ID "+fieldID.getText());
                //System.out.println(fieldAuthor.getText());
            }
            if(!(fieldName.getText()).equals("Name")&&(fieldName.getText()).length()>0)
            {
                aktualizuj = st.executeUpdate("UPDATE app.sculptures SET name = '"+fieldName.getText()+"' WHERE sculpture_id  = "+fieldID.getText());
                //labelInfo.setText("Zaktualizowano rzezbe o  ID "+fieldID.getText());
            }
            if(!(fieldGendre.getText()).equals("Gendre")&&(fieldGendre.getText()).length()>0)
            {
                aktualizuj = st.executeUpdate("UPDATE app.sculptures SET gendre = '"+fieldGendre.getText()+"' WHERE sculpture_id  = "+fieldID.getText());
                //labelInfo.setText("Zaktualizowano rzezbe o  ID "+fieldID.getText());
            }
            if(!(fieldMaterial.getText()).equals("Material")&&(fieldMaterial.getText()).length()>0)
            {
                aktualizuj = st.executeUpdate("UPDATE app.sculptures SET Material = '"+fieldMaterial.getText()+"' WHERE sculpture_id  = "+fieldID.getText());
                //labelInfo.setText("Zaktualizowano rzezbe o  ID "+fieldID.getText());
            }*/
            if(!(fieldUSD.getText()).equals("USD price")&&(fieldUSD.getText()).length()>0)
            {
                System.out.println(fieldUSD.getText());
                aktualizuj = st.executeUpdate("UPDATE app.sculptures SET usd_price = "+fieldUSD.getText()+" WHERE sculpture_id  = "+fieldID.getText());
                //labelInfo.setText("Zaktualizowano rzezbe o  ID "+fieldID.getText());
            }
            aktualizuj = st.executeUpdate("UPDATE app.sculptures SET museum_property = '"+checkboxMP.isSelected()+"' WHERE sculpture_id  = "+fieldID.getText());
            //System.out.println(checkboxMP.isSelected());
            //tPole.setText("Dodano nowa rzezbe");
            labelInfo.setText("Zaktualizowano rzezbe o  ID "+fieldID.getText());
        } catch (Exception ex) {
            labelInfo.setText("Nie udalo sie zaktualizowac rzezby o ID "+fieldID.getText());
        }
    }//GEN-LAST:event_bttnUpdateSculptureActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(dbAktualizuj.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(dbAktualizuj.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(dbAktualizuj.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(dbAktualizuj.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new dbAktualizuj().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bttnUpdateSculpture;
    private javax.swing.JCheckBox checkboxMP;
    private javax.swing.JTextField fieldAuthor;
    private javax.swing.JTextField fieldGendre;
    private javax.swing.JTextField fieldID;
    private javax.swing.JTextField fieldMaterial;
    private javax.swing.JTextField fieldName;
    private javax.swing.JTextField fieldUSD;
    private javax.swing.JLabel infoLabel;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel labelInfo;
    // End of variables declaration//GEN-END:variables
}
