INSERT INTO APP.SCULPTURES (SCULPTURE_ID, "NAME", AUTOR, GENRE, MATERIAL, USD_PRICE, MASEUM_PROPERTY) 
	VALUES (1, 'Kelpies', 'Andy Scott', 'mithology', 'steel', 1000, false);
INSERT INTO APP.SCULPTURES (SCULPTURE_ID, "NAME", AUTOR, GENRE, MATERIAL, USD_PRICE, MASEUM_PROPERTY) 
	VALUES (2, 'Juodasis Vaiduoklis', 'Svajunas Jurkus', 'horror', 'bronze', 200, false);
INSERT INTO APP.SCULPTURES (SCULPTURE_ID, "NAME", AUTOR, GENRE, MATERIAL, USD_PRICE, MASEUM_PROPERTY) 
	VALUES (3, 'Pieta', 'Michelangelo', 'renaissance', 'marble', 2000, true);
INSERT INTO APP.SCULPTURES (SCULPTURE_ID, "NAME", AUTOR, GENRE, MATERIAL, USD_PRICE, MASEUM_PROPERTY) 
	VALUES (4, 'David', 'Donatello', 'antique', 'bronze', 500, true);
INSERT INTO APP.SCULPTURES (SCULPTURE_ID, "NAME", AUTOR, GENRE, MATERIAL, USD_PRICE, MASEUM_PROPERTY) 
	VALUES (5, 'Sphinx', 'unknown', 'ancient', 'limestone', 10000, false);
INSERT INTO APP.SCULPTURES (SCULPTURE_ID, "NAME", AUTOR, GENRE, MATERIAL, USD_PRICE, MASEUM_PROPERTY) 
	VALUES (6, 'Thinker', 'Auguste Rodin', 'antique', 'bronze', 4000, true);
INSERT INTO APP.SCULPTURES (SCULPTURE_ID, "NAME", AUTOR, GENRE, MATERIAL, USD_PRICE, MASEUM_PROPERTY) 
	VALUES (7, 'Guitar', 'Pablo Picasso', 'stll life', 'cardboard', 700, true);
INSERT INTO APP.SCULPTURES (SCULPTURE_ID, "NAME", AUTOR, GENRE, MATERIAL, USD_PRICE, MASEUM_PROPERTY) 
	VALUES (8, 'Bicycle Wheel', 'Marcel Duchamp', 'installation', 'ready-made', 1000, true);
INSERT INTO APP.SCULPTURES (SCULPTURE_ID, "NAME", AUTOR, GENRE, MATERIAL, USD_PRICE, MASEUM_PROPERTY) 
	VALUES (9, 'Air', 'Aristide Maillol', 'impression', 'bronze', 6000, true);
INSERT INTO APP.SCULPTURES (SCULPTURE_ID, "NAME", AUTOR, GENRE, MATERIAL, USD_PRICE, MASEUM_PROPERTY) 
	VALUES (10, 'Spider', 'Louise Bourgeois', 'monument', 'steel', 3000, false);
INSERT INTO APP.SCULPTURES (SCULPTURE_ID, "NAME", AUTOR, GENRE, MATERIAL, USD_PRICE, MASEUM_PROPERTY) 
	VALUES (11, 'Angel of te North', 'Antony Gormley', 'minimalism', 'steel', 1500, false);