package Hibernate;
// Generated 2022-05-08 13:01:27 by Hibernate Tools 4.3.1



/**
 * Hashedstrings generated by hbm2java
 */
public class Hashedstrings  implements java.io.Serializable {


     private int idH;
     private String hashedstring;

    public Hashedstrings() {
    }

    public Hashedstrings(int idH, String hashedstring) {
       this.idH = idH;
       this.hashedstring = hashedstring;
    }
   
    public int getIdH() {
        return this.idH;
    }
    
    public void setIdH(int idH) {
        this.idH = idH;
    }
    public String getHashedstring() {
        return this.hashedstring;
    }
    
    public void setHashedstring(String hashedstring) {
        this.hashedstring = hashedstring;
    }




}


