package Trwalosc;
// Generated 2022-04-17 23:12:58 by Hibernate Tools 4.3.1



/**
 * Pictures generated by hbm2java
 */
public class Pictures  implements java.io.Serializable {


     private int imageId;
     private String name;
     private String author;
     private String type;
     private String form;
     private Integer usdPrice;
     private Boolean museumProperty;

    public Pictures() {
    }

	
    public Pictures(int imageId) {
        this.imageId = imageId;
    }
    public Pictures(int imageId, String name, String author, String type, String form, Integer usdPrice, Boolean museumProperty) {
       this.imageId = imageId;
       this.name = name;
       this.author = author;
       this.type = type;
       this.form = form;
       this.usdPrice = usdPrice;
       this.museumProperty = museumProperty;
    }
   
    public int getImageId() {
        return this.imageId;
    }
    
    public void setImageId(int imageId) {
        this.imageId = imageId;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public String getAuthor() {
        return this.author;
    }
    
    public void setAuthor(String author) {
        this.author = author;
    }
    public String getType() {
        return this.type;
    }
    
    public void setType(String type) {
        this.type = type;
    }
    public String getForm() {
        return this.form;
    }
    
    public void setForm(String form) {
        this.form = form;
    }
    public Integer getUsdPrice() {
        return this.usdPrice;
    }
    
    public void setUsdPrice(Integer usdPrice) {
        this.usdPrice = usdPrice;
    }
    public Boolean getMuseumProperty() {
        return this.museumProperty;
    }
    
    public void setMuseumProperty(Boolean museumProperty) {
        this.museumProperty = museumProperty;
    }




}


