/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package lab1.derby;
import lab1.derby.DbManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import lab1.derby.DbManager;
import static lab1.derby.DbManager.QUERY;

/**
 *
 * @author student
 */
public class DbOkno extends javax.swing.JFrame {

    private boolean connect;

    /**
     * Creates new form DbOkno
     */
    public DbOkno() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tPole = new javax.swing.JTextArea();
        labelInfo = new javax.swing.JLabel();
        bttnPolacz = new javax.swing.JButton();
        bttnRozlacz = new javax.swing.JButton();
        bttnWypisz = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        paneImie = new javax.swing.JTextPane();
        jScrollPane2 = new javax.swing.JScrollPane();
        paneNazwisko = new javax.swing.JTextPane();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        bttnDodaj = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        tPole.setColumns(20);
        tPole.setRows(5);
        jScrollPane1.setViewportView(tPole);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(labelInfo)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 222, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(labelInfo))
        );

        bttnPolacz.setText("Połącz");
        bttnPolacz.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bttnPolaczActionPerformed(evt);
            }
        });

        bttnRozlacz.setText("Rozłącz");
        bttnRozlacz.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bttnRozlaczActionPerformed(evt);
            }
        });

        bttnWypisz.setText("Wypisz");
        bttnWypisz.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bttnWypiszActionPerformed(evt);
            }
        });

        jScrollPane3.setViewportView(paneImie);

        jScrollPane2.setViewportView(paneNazwisko);

        jLabel1.setText("Imie");

        jLabel2.setText("Nazwisko");

        bttnDodaj.setText("Dodaj");
        bttnDodaj.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bttnDodajActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(29, 29, 29)
                        .addComponent(bttnDodaj)))
                .addGap(0, 86, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(bttnDodaj)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2))
                        .addGap(4, 4, 4)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(47, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addComponent(bttnPolacz)
                .addGap(18, 18, 18)
                .addComponent(bttnRozlacz)
                .addGap(18, 18, 18)
                .addComponent(bttnWypisz)
                .addGap(0, 0, Short.MAX_VALUE))
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bttnPolacz)
                    .addComponent(bttnRozlacz)
                    .addComponent(bttnWypisz))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bttnPolaczActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bttnPolaczActionPerformed
        try {
            // TODO add your handling code here:
            connect = DbManager.Connect();
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(DbOkno.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(DbOkno.class.getName()).log(Level.SEVERE, null, ex);
        }
        if (connect) {
            tPole.setText("Połączono");
        } else {
            tPole.setText("Nie połączono");
        }
    }//GEN-LAST:event_bttnPolaczActionPerformed

    private void bttnRozlaczActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bttnRozlaczActionPerformed
        // TODO add your handling code here:
        try {
        connect = DbManager.Disconnect();
        } catch (SQLException ex) {
        Logger.getLogger(DbOkno.class.getName()).log(Level.SEVERE, null, ex);
        }
        if (connect) {
        tPole.setText("Rozłączono");
        } else {
        tPole.setText("Nie rozłączono");
        } 
    }//GEN-LAST:event_bttnRozlaczActionPerformed

    private void bttnWypiszActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bttnWypiszActionPerformed
        // TODO add your handling code here:
        try {
            if (connect) {
                String out = DbManager.getData();
                tPole.removeAll();
                tPole.setText(out);
            } else {
                tPole.setText("Nie połączono");
            }
        } catch (SQLException ex) {
            Logger.getLogger(DbOkno.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_bttnWypiszActionPerformed

    private void bttnDodajActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bttnDodajActionPerformed
        // TODO add your handling code here:
        try {
            Statement st = null;
            st = DbManager.conn.createStatement();
            String getNmbID = "select count(ID) as nmbsID from app.pracownicy";
            int nmbID = 0;
            ResultSet rs = st.executeQuery(getNmbID);
            while(rs.next()){
            nmbID = rs.getInt("nmbsID");
            }
            //tPole.setText(Integer.toString(nmbID));
            //tPole.setText("dziala");
            int lNazwisko = (paneNazwisko.getText()).length();
            int lImie = (paneImie.getText()).length();
            if(lNazwisko<1||lImie<1){
                throw new ArithmeticException("Imie lub nazwisko jest puste");    
            }
            nmbID++;
            String dodaj = "INSERT INTO APP.PRACOWNICY VALUES ("+Integer.toString(nmbID)+", '" +paneImie.getText()+"', '"+paneNazwisko.getText()+"')";
            int pom = st.executeUpdate(dodaj);
            tPole.setText("Dodano nowego pracownika");
        } catch (Exception ex) {
            tPole.setText("Nie udalo sie dodac nowego pracownika");
        }
    }//GEN-LAST:event_bttnDodajActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DbOkno.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DbOkno.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DbOkno.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DbOkno.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DbOkno().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bttnDodaj;
    private javax.swing.JButton bttnPolacz;
    private javax.swing.JButton bttnRozlacz;
    private javax.swing.JButton bttnWypisz;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JLabel labelInfo;
    private javax.swing.JTextPane paneImie;
    private javax.swing.JTextPane paneNazwisko;
    private javax.swing.JTextArea tPole;
    // End of variables declaration//GEN-END:variables

}
